### ISSUE TITLE
Panic on load, attempting to substract with overflow when using more than the rust binary.

### ISSUE THREAD

**Issue by xacrimon** [rust-osdev/multiboot2-elf64#39]

**Comment by phil-opp** [comment]
Could you explain in more detail what you're trying to do? What do you mean with "when using more than the rust binary"?

**Comment by phil-opp** [comment]
So you're linking multiple static libraries into a final kernel binary and then try to load the multiboot info somewhere in it?

Could you give us some more information where the panic happens, in which line and in which file (you can output this information in your panic handler)? A GDB backtrace would be even better (start QEMU with `-s`, then connect a GBD instance, and then execute `backtrace`).

**Comment by xacrimon** [comment]
Oops, I was using the old 1.0 version from your blog. See #40 as I will be writing some documentation soon.
