### ISSUE TITLE
Implement Send on BootInformation?

### ISSUE THREAD

**Issue by roblabla** [rust-osdev/multiboot2-elf64#47]
BootInformation doesn't implement Send, because it contains a raw pointer. From the nomicon: 

> A type is Send if it is safe to send it to another thread.

The pointer inside the BootInformation is const, so we cannot modify it across threads anyways. Is there any downside to doing an `unsafe impl Send for BootInformation {}` ? My goal is to store it inside a `spin::Once<T>`, and that requires it to be Send.

**Comment by phil-opp** [comment]
Hi @roblabla, thanks for opening this issue and sorry for the delay.

I don't see any problem with implementing `Send`, because we don't provide methods to modify the boot information and the pointers should have `'static` lifetime.

@rust-osdev/multiboot2 What do you think?

**Comment by phil-opp** [comment]
ping @rust-osdev/multiboot2

**Comment by IsaacWoods** [comment]
As far as I can see, it’s safe to implement `Send` as long as we don’t ever unsafely cast that pointer to be mutable (afaik we never do)

**Comment by xacrimon** [comment]
I agree with you @IsaacWoods

**Comment by xacrimon** [comment]
Alright. Extracting into your own structs seems to be the desired solution. Please reopen if you have other views.
